version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_nest_restaurant
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: restaurant
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
